// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anvlzsrwtvtlvfgjkzce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFudmx6c3J3dHZ0bHZmZ2premNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjE3MzMsImV4cCI6MjA2OTg5NzczM30.7V1GBK-760G2APJZOZlwxRJCRRKCODZGZUpQhYgFWsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});